# Generated by Django 4.0.1 on 2022-02-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cartoon',
            new_name='Film',
        ),
    ]
